name: Glimpse Continuous Integration
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Glimpse CI
    if: false # always skip running to avoid using up minutes
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Test
        run: |
          xcodebuild -scheme "Glimpse" build CODE_SIGNING_ALLOWED=NO 
