name: Glimpse CI
  
on:
  push:
    branches: '*'
    tags: '*'

    # build at 6AM & 6PM UTC
    schedule: 
      - cron:  '0 3,6,9,12,15,18,21,24 * * *'

jobs:
  test-job:
    name: Glimpse Tests
    runs-on: macos-11.0
    timeout-minutes: 240

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}


      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # https://github.com/actions/checkout/issues/100
          token: ${{ secrets.ACCESS_TOKEN }}

      # not required, but helps speed up rebuilding unchanged projects
      - name: Cache Derived data
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ddata-${{ hashFiles('**/*.pbxproj') }}
          restore-keys: ddata-
          
      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme "Glimpse" \
            | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      - name: Upload Test Output
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: build/reports/tests.html

  release-job:
    name: Glimpse Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    timeout-minutes: 240

    environment: Signing
    env:
      ORG_NAME: glimpseio 
      REPO_NAME: GIO
      APP_NAME: Glimpse
      TEST_NAME: Glimpse
      CONFIGURATION: Release
      #CONFIGURATION: Debug
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # https://github.com/actions/checkout/issues/100
          token: ${{ secrets.ACCESS_TOKEN }}

      # not required, but helps speed up rebuilding unchanged projects
      - name: Cache Derived data
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ddata-${{ hashFiles('**/*.pbxproj') }}
          restore-keys: ddata-

      - name: "Configure Versions"
        id: config
        run: |
          echo "::set-output name=tagname::${GITHUB_REF#refs/*/}"
          echo "::set-output name=buildnumber::$(git rev-list --count ${GITHUB_REF#refs/*/})"

      - name: "Setup Export"
        run: |
          mkdir -p Export/
          echo '<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"><channel><item><enclosure sparkle:version="${{ steps.config.outputs.buildnumber }}" sparkle:shortVersionString="${{ steps.config.outputs.tagname }}" url="https://github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}/releases/download/${{ steps.config.outputs.tagname }}/${{ env.APP_NAME }}.zip"></enclosure></item></channel></rss>' > Export/appcast.xml
          cat Export/appcast.xml

      - name: "Build Archive"
        run: |
          xcodebuild archive \
            -configuration "${{ env.CONFIGURATION }}" \
            -scheme "${{ env.APP_NAME }}" \
            -archivePath "Export/${{ env.APP_NAME }}.xcarchive" \
            MARKETING_VERSION="${{ steps.config.outputs.tagname }}" \
            CURRENT_PROJECT_VERSION="${{ steps.config.outputs.buildnumber }}"

      - name: "Notarize"
        uses: hubomatic/hubomat@0.1.7
        with:
          verbose: true
          timeout: 180 # minutes
          scheme: "${{ env.APP_NAME }}"

          export-path: "Export/"
          archive-path: "Export/${{ env.APP_NAME }}.xcarchive"
          product-path: "Export/${{ env.APP_NAME }}.app"
          artifact-path: "Export/${{ env.APP_NAME }}.zip"

          team-id: ${{ secrets.TEAM_ID }}
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}

          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Upload Build Artifact Zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}.zip
          path: Export/${{ env.APP_NAME }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          #body_path: RELEASE_NOTES.md
          files: |
            CHANGELOG.md
            RELEASE_NOTES.md
            Export/appcast.xml
            Export/${{ env.APP_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

