name: Glimpse Continuous Integration
  
on:
  push:
    branches: '*'
    tags: '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:
  build:
    name: Glimpse CI
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build
        run: |
          xcodebuild -scheme "Glimpse" build CODE_SIGNING_ALLOWED=NO 
      - name: Test
        run: |
          xcodebuild -scheme "Glimpse" test CODE_SIGNING_ALLOWED=NO 
      - name: Archive
        run: |
          xcodebuild -scheme "Glimpse" archive CODE_SIGNING_ALLOWED=NO 
